name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ✅ Use Node.js 20 to match the required engine for react-router v7.4.0
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # ✅ Frontend build with permission fix for react-scripts
      - name: Install Frontend Dependencies and Build
        run: |
          cd frontend
          npm install
          chmod +x ./node_modules/.bin/react-scripts
          npm run build

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Run Backend Tests
        run: |
          cd backend
          npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "jb-studios-app"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
